In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("customer_support_tickets.csv")

df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [2]:
df.shape

(8469, 17)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 4.7 MB

In [4]:
df.columns

Index(['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age',
       'Customer Gender', 'Product Purchased', 'Date of Purchase',
       'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status',
       'Resolution', 'Ticket Priority', 'Ticket Channel',
       'First Response Time', 'Time to Resolution',
       'Customer Satisfaction Rating'],
      dtype='str')

In [5]:
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

In [6]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_description', 'ticket_status',
       'resolution', 'ticket_priority', 'ticket_channel',
       'first_response_time', 'time_to_resolution',
       'customer_satisfaction_rating'],
      dtype='str')

In [8]:
# check for duplicate in ticket_id column
df["ticket_id"].duplicated().sum()

np.int64(0)

In [9]:
# Checking Missing values
df.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
product_purchased                  0
date_of_purchase                   0
ticket_type                        0
ticket_subject                     0
ticket_description                 0
ticket_status                      0
resolution                      5700
ticket_priority                    0
ticket_channel                     0
first_response_time             2819
time_to_resolution              5700
customer_satisfaction_rating    5700
dtype: int64

In [10]:
# see the percent in missing values
null_summary = pd.DataFrame({
    "null_count": df.isnull().sum(),
    "null_percentage": (df.isnull().sum() / len(df) * 100).round(2)
})

null_summary.sort_values("null_count", ascending=False)

                              null_count  null_percentage
customer_satisfaction_rating        5700            67.30
time_to_resolution                  5700            67.30
resolution                          5700            67.30
first_response_time                 2819            33.29
ticket_description                     0             0.00
ticket_channel                         0             0.00
ticket_priority                        0             0.00
ticket_status                          0             0.00
ticket_id                              0             0.00
customer_name                          0             0.00
ticket_type                            0             0.00
date_of_purchase                       0             0.00
product_purchased                      0             0.00
customer_gender                        0             0.00
customer_age                           0             0.00
customer_email                         0             0.00
ticket_subject                         0             0.00

In [12]:
# Giving unknown to the customer_gender and ticket_channel
categorical_cols = [
    "customer_gender",
    "ticket_channel"
]

for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

In [13]:
df["ticket_subject"] = df["ticket_subject"].fillna("No Subject")

df["ticket_description"] = df["ticket_description"].fillna("No Description")

In [14]:
df["resolution"] = df["resolution"].fillna("Not Resolved")

In [15]:
df["customer_age"].isnull().sum()

np.int64(0)

In [16]:
df["customer_age"].describe()

count    8469.000000
mean       44.026804
std        15.296112
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: customer_age, dtype: float64

In [17]:
df["customer_age"] = df["customer_age"].fillna(
    df["customer_age"].median()
)

In [18]:
# Date/time nulls
df["date_of_purchase"] = pd.to_datetime(
    df["date_of_purchase"],
    errors="coerce"
)

df["first_response_time"] = pd.to_datetime(
    df["first_response_time"],
    errors="coerce"
)

df["time_to_resolution"] = pd.to_datetime(
    df["time_to_resolution"],
    errors="coerce"
)

In [20]:
df.isnull().sum()

ticket_id                          0
customer_name                      0
customer_email                     0
customer_age                       0
customer_gender                    0
product_purchased                  0
date_of_purchase                   0
ticket_type                        0
ticket_subject                     0
ticket_description                 0
ticket_status                      0
resolution                         0
ticket_priority                    0
ticket_channel                     0
first_response_time             2819
time_to_resolution              5700
customer_satisfaction_rating    5700
dtype: int64

In [21]:
df[col].value_counts()

ticket_channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

In [23]:
# Convert date_of_purchase to datetime
df["date_of_purchase"] = pd.to_datetime(
    df["date_of_purchase"],
    errors="coerce"
)

In [24]:
#Convert First Response Time
df["first_response_time"] = pd.to_datetime(
    df["first_response_time"],
    errors="coerce"
)

In [25]:
#Convert Time to Resolution
df["time_to_resolution"] = pd.to_datetime(
    df["time_to_resolution"],
    errors="coerce"
)

In [26]:
#Create resolution time in hours
df["resolution_hours"] = (
    df["time_to_resolution"] -
    df["first_response_time"]
).dt.total_seconds() / 3600

In [28]:
#Create first response date/time features
df["response_date"] = df["first_response_time"].dt.date
df["response_hour"] = df["first_response_time"].dt.hour
df["response_month"] = df["first_response_time"].dt.month
df["response_day"] = df["first_response_time"].dt.day_name()

In [29]:
# Validate customer Age
df["customer_age"].describe()

count    8469.000000
mean       44.026804
std        15.296112
min        18.000000
25%        31.000000
50%        44.000000
75%        57.000000
max        70.000000
Name: customer_age, dtype: float64

In [30]:
#Validate satisfaction rating
df["customer_satisfaction_rating"].value_counts(dropna=False).sort_index()

customer_satisfaction_rating
1.0     553
2.0     549
3.0     580
4.0     543
5.0     544
NaN    5700
Name: count, dtype: int64

In [ ]:
#Check Uniqueness
print(df["ticket_status"].unique())
print(df["ticket_priority"].unique())
print(df["ticket_type"].unique())
print(df["ticket_channel"].unique())
print(df["customer_gender"].unique())

In [32]:
#Handle missing values logically
df["resolution"] = df["resolution"].fillna("Not Resolved")

In [38]:


# Convert datetime columns properly
df["first_response_time"] = pd.to_datetime(
    df["first_response_time"],
    errors="coerce"
)

df["time_to_resolution"] = pd.to_datetime(
    df["time_to_resolution"],
    errors="coerce"
)

# Calculate resolution time in hours
df["resolution_hours"] = (
    df["time_to_resolution"] - df["first_response_time"]
).dt.total_seconds() / 3600

# Create response date/time features
df["response_date"] = df["first_response_time"].dt.date
df["response_hour"] = df["first_response_time"].dt.hour
df["response_month"] = df["first_response_time"].dt.month
df["response_day"] = df["first_response_time"].dt.day_name()

In [39]:
df.columns

Index(['ticket_id', 'customer_name', 'customer_email', 'customer_age',
       'customer_gender', 'product_purchased', 'date_of_purchase',
       'ticket_type', 'ticket_subject', 'ticket_description', 'ticket_status',
       'resolution', 'ticket_priority', 'ticket_channel',
       'first_response_time', 'time_to_resolution',
       'customer_satisfaction_rating', 'resolution_hours', 'response_date',
       'response_hour', 'response_month', 'response_day'],
      dtype='str')

In [35]:
df["ticket_description"] = df.apply(
    lambda row: row["ticket_description"].replace(
        "{product_purchased}",
        str(row["product_purchased"])
    ) if pd.notna(row["ticket_description"]) and pd.notna(row["product_purchased"])
    else row["ticket_description"],
    axis=1
)

In [36]:
df.head(5)

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,...,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_hours,response_date,response_hour,response_month,response_day
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the GoPro Hero. Pleas...,...,Critical,Social media,2023-06-01 12:15:36,NaT,NaN,NaN,2023-06-01,12.0,6.0,Thursday
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the LG Smart TV. Plea...,...,Critical,Chat,2023-06-01 16:45:38,NaT,NaN,NaN,2023-06-01,16.0,6.0,Thursday
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my Dell XPS. The Del...,...,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0,6.850000,2023-06-01,11.0,6.0,Thursday
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the Microsoft Office....,...,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0,-5.533333,2023-06-01,7.0,6.0,Thursday
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the Autodesk AutoCAD....,...,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0,19.683333,2023-06-01,0.0,6.0,Thursday

# Connecting Jupyter Notebook to SSMS

In [40]:
# ============================================
# LOAD PANDAS DATAFRAME INTO SQL SERVER
# ============================================

!pip install -q pyodbc sqlalchemy pandas

import pandas as pd
from sqlalchemy import create_engine

# SQL Server details
server = r"DESKTOP-PT1D5QM\SQLEXPRESS"
database = "support_ticket_rootcauseanalysis"

# Create connection
connection_string = (
    f"mssql+pyodbc://@{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = create_engine(connection_string)

# Check that your DataFrame exists
print("Pandas dataset shape:", df.shape)

# Name of the SQL Server table
table_name = "support_ticket_RCA"

# Upload DataFrame to SQL Server
df.to_sql(
    table_name,
    con=engine,
    if_exists="replace",
    index=False
)

print(f"✅ Dataset successfully loaded into SQL Server!")
print(f"✅ Table created: {table_name}")
print(f"✅ Rows inserted: {len(df)}")

# Verify the table
check = pd.read_sql(
    f"SELECT TOP 5 * FROM [{table_name}]",
    engine
)

display(check)

Pandas dataset shape: (8469, 22)
✅ Dataset successfully loaded into SQL Server!
✅ Table created: support_ticket_RCA
✅ Rows inserted: 8469

,ticket_id,customer_name,customer_email,customer_age,customer_gender,product_purchased,date_of_purchase,ticket_type,ticket_subject,ticket_description,...,ticket_priority,ticket_channel,first_response_time,time_to_resolution,customer_satisfaction_rating,resolution_hours,response_date,response_hour,response_month,response_day
0,476,Matthew Wilson,wilsondavid@example.org,45,Male,LG Washing Machine,2020-06-28,Billing inquiry,Display issue,I'm having an issue with the LG Washing Machin...,...,High,Chat,NaT,None,None,None,None,NaN,NaN,NaN
1,477,Hunter Armstrong,schultzdaniel@example.net,59,Female,HP Pavilion,2020-08-30,Refund request,Installation support,I'm having an issue with the HP Pavilion. Plea...,...,Low,Social media,NaT,None,None,None,None,NaN,NaN,NaN
2,478,Sandra Hale,ritterwalter@example.org,45,Male,Sony PlayStation,2021-10-14,Cancellation request,Installation support,I'm having an issue with the Sony PlayStation....,...,Critical,Email,NaT,None,None,None,None,NaN,NaN,NaN
3,479,James David,james81@example.org,38,Female,Lenovo ThinkPad,2021-10-11,Billing inquiry,Software bug,I'm having an issue with the Lenovo ThinkPad. ...,...,Low,Social media,2023-06-01 07:29:35,None,None,None,2023-06-01,7.0,6.0,Thursday
4,480,Samantha Vega,hhall@example.com,46,Male,Dell XPS,2020-01-07,Refund request,Product setup,I'm having an issue with the Dell XPS. Please ...,...,Critical,Phone,NaT,None,None,None,None,NaN,NaN,NaN